// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://rulmusmbnrbxvzfrkztm.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1bG11c21ibnJieHZ6ZnJrenRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyMTEyMDYsImV4cCI6MjA0ODc4NzIwNn0.8AODLrsROG8Fd9hMc-WSltowLOuYYssnrx7peoNDngw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);